version: "2"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./public:/var/www/LaraPress/public
    ports:
      - 80:80
    links:
      - phpfpm
    depends_on:
      - phpfpm
  phpfpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/www/LaraPress
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=LaraPress_db
      - DB_USERNAME=LaraPress
      - DB_PASSWORD=LaraPress
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=LaraPress
      - MYSQL_DATABASE=LaraPress_db
      - MYSQL_USER=LaraPress
      - MYSQL_PASSWORD=LaraPress
